// sub-app-react/src/pages/Dashboard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import type { UserData } from '../bootstrap';

interface DashboardProps {
  userData: UserData | null;
}

/**
 * Dashboard page — mirrors the Angular sub-app's dashboard.
 *
 * Displays the shared auth state received from the Angular shell
 * and provides links to detail pages to demonstrate internal routing.
 */
export function Dashboard({ userData }: DashboardProps) {
  return (
    <div className="dashboard">
      <h1>Sub-App React Dashboard</h1>
      <p className="badge react-badge">React micro frontend</p>

      <section className="auth-status">
        <h2>Shared Auth State</h2>
        {userData ? (
          <div className="auth-card authenticated">
            <p className="status">Authenticated</p>
            <dl>
              <dt>Name</dt>
              <dd>{userData.displayName}</dd>
              <dt>Email</dt>
              <dd>{userData.email}</dd>
              <dt>Role</dt>
              <dd>{userData.role}</dd>
              <dt>ID</dt>
              <dd>{userData.id}</dd>
            </dl>
            <p className="explanation">
              This data comes from the Angular shell's <code>AuthService</code> in{' '}
              <code>@skv/shared</code>. The shell passes it to this React micro
              frontend via Custom Element attributes — bridging Angular signals
              to React props through the DOM.
            </p>
          </div>
        ) : (
          <div className="auth-card unauthenticated">
            <p className="status">Not authenticated</p>
            <p className="explanation">
              Go back to the shell header and click <strong>Log in</strong>.
              Then return here — you'll see the user data appear without any
              reload, because the Angular <code>WrapperComponent</code> passes
              the auth state from the shared <code>AuthService</code> into this
              React app via element attributes.
            </p>
          </div>
        )}
      </section>

      <section className="nav-demo">
        <h2>React Internal Routing</h2>
        <p>
          This remote uses React Router for its own child routes, all rendered
          inside the Angular shell's <code>&lt;router-outlet&gt;</code>:
        </p>
        <div className="detail-links">
          <Link to="/details/1" className="detail-link">View Item 1</Link>
          <Link to="/details/2" className="detail-link">View Item 2</Link>
          <Link to="/details/3" className="detail-link">View Item 3</Link>
        </div>
      </section>
    </div>
  );
}

// sub-app-module/src/app/pages/dashboard/dashboard.component.ts
import { Component, inject } from '@angular/core';
import { AuthService } from '@skv/shared';

@Component({
  standalone: false,
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent {
  private readonly auth = inject(AuthService);
  readonly isAuthenticated = this.auth.isAuthenticated;
  readonly currentUser = this.auth.currentUser;
}

<div class="dashboard">
  <h1>Sub-App Module Dashboard</h1>
  <p class="badge">Remote micro frontend (NgModule)</p>

  <section class="auth-status">
    <h2>Shared Auth State</h2>
    @if (isAuthenticated()) {
      <div class="auth-card authenticated">
        <p class="status">Authenticated</p>
        <dl>
          <dt>Name</dt>
          <dd>{{ currentUser()!.displayName }}</dd>
          <dt>Email</dt>
          <dd>{{ currentUser()!.email }}</dd>
          <dt>Role</dt>
          <dd>{{ currentUser()!.role }}</dd>
          <dt>ID</dt>
          <dd>{{ currentUser()!.id }}</dd>
        </dl>
        <p class="explanation">
          This data comes from the <code>AuthService</code> in
          <code>&#64;skv/shared</code>. This remote uses <strong>NgModules</strong>
          (not standalone components), yet it shares the same singleton
          <code>AuthService</code> instance as the shell and the standalone sub-app.
        </p>
      </div>
    } @else {
      <div class="auth-card unauthenticated">
        <p class="status">Not authenticated</p>
        <p class="explanation">
          Go back to the shell header and click <strong>Log in</strong>.
          Then return here — you'll see the user data appear without any
          reload. This NgModule-based remote reads the same
          <code>AuthService</code> singleton as the standalone sub-app.
        </p>
      </div>
    }
  </section>

  <section class="nav-demo">
    <h2>Sub-App Module Internal Routing</h2>
    <p>
      This remote uses <code>RouterModule.forChild()</code> inside an NgModule,
      which the shell lazy-loads. The routing works identically to the standalone sub-app:
    </p>
    <div class="detail-links">
      <a [routerLink]="['details', '1']" class="detail-link">View Item 1</a>
      <a [routerLink]="['details', '2']" class="detail-link">View Item 2</a>
      <a [routerLink]="['details', '3']" class="detail-link">View Item 3</a>
    </div>
  </section>
</div>
