// sub-app-react/src/pages/Details.tsx
import React from 'react';
import { useParams, Link } from 'react-router-dom';

/**
 * Details page — mirrors the Angular sub-app's details page.
 *
 * Reads the :id route parameter via React Router's useParams() hook,
 * similar to how the Angular version uses input.required<string>()
 * with withComponentInputBinding().
 */
export function Details() {
  const { id } = useParams<{ id: string }>();

  return (
    <div className="details">
      <Link to="/" className="back-link">Back to dashboard</Link>

      <h1>Details for Item {id}</h1>
      <p className="badge react-badge">React micro frontend — child route</p>

      <div className="detail-card">
        <p>
          This page demonstrates that the React sub-app manages its own child
          routes internally using React Router. The URL
          is <code>/sub-app-react/details/{id}</code> — the shell's Angular
          Router delegates everything under <code>/sub-app-react</code> to this
          remote's Custom Element, and React Router handles the rest.
        </p>
        <p>
          The route parameter <code>:id</code> is read via React
          Router's <code>useParams()</code> hook — the React equivalent of
          Angular's <code>input.required()</code> with route binding.
        </p>
      </div>
    </div>
  );
}

// sub-app-module/src/app/pages/details/details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  standalone: false,
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrl: './details.component.scss',
})
export class DetailsComponent implements OnInit {
  id = '';

  constructor(private readonly route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id') ?? '';
  }
}

<div class="details">
  <a routerLink="../.." class="back-link">Back to dashboard</a>

  <h1>Details for Item {{ id }}</h1>
  <p class="badge">Remote micro frontend — child route (NgModule)</p>

  <div class="detail-card">
    <p>
      This page demonstrates that the NgModule-based sub-app manages its own
      child routes. The URL is <code>/sub-app-module/details/{{ id }}</code> —
      the shell's router delegates everything under <code>/sub-app-module</code>
      to this remote's <code>RemoteModule</code> which uses
      <code>RouterModule.forChild()</code>.
    </p>
    <p>
      The route parameter <code>:id</code> is read via
      <code>ActivatedRoute.snapshot.paramMap</code> — the traditional NgModule
      approach. Compare with the standalone sub-app which uses
      <code>input.required()</code> with <code>withComponentInputBinding()</code>.
    </p>
  </div>
</div>
